[theme]
base = "light"
primaryColor = "#267969"
backgroundColor = "#f4f6f8"
secondaryBackgroundColor = "#eaf0f2"
textColor = "#142d39"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#102631"
secondaryBackgroundColor = "#1d3743"
textColor = "#e1ebed"
primaryColor = "#86d7bb"

[server]
headless = true
maxUploadSize = 15

[browser]
gatherUsageStats = false
